/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frameApp;

/**
 *
 * @author acer
 */
public class frameAnggota extends javax.swing.JFrame {

    /**
     * Creates new form frameAnggota
     */
    public frameAnggota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputIDAnggota = new javax.swing.JTextField();
        inputNamaAnggota = new javax.swing.JTextField();
        inputNoHPAnggota = new javax.swing.JTextField();
        inputProdi = new javax.swing.JTextField();
        inputFakultas = new javax.swing.JTextField();
        inputAlamatAnggota = new javax.swing.JTextField();
        inputTahunMasuk = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAnggota = new javax.swing.JTable();
        bgAnggota = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        inputIDAnggota.setBackground(new java.awt.Color(222, 217, 186));
        inputIDAnggota.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        inputIDAnggota.setForeground(new java.awt.Color(255, 204, 0));
        inputIDAnggota.setBorder(null);
        inputIDAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIDAnggotaActionPerformed(evt);
            }
        });
        getContentPane().add(inputIDAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 162, 400, 30));

        inputNamaAnggota.setBackground(new java.awt.Color(222, 217, 186));
        inputNamaAnggota.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        inputNamaAnggota.setForeground(new java.awt.Color(255, 204, 0));
        inputNamaAnggota.setBorder(null);
        inputNamaAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaAnggotaActionPerformed(evt);
            }
        });
        getContentPane().add(inputNamaAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 400, 30));

        inputNoHPAnggota.setBackground(new java.awt.Color(222, 217, 186));
        inputNoHPAnggota.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        inputNoHPAnggota.setForeground(new java.awt.Color(255, 204, 0));
        inputNoHPAnggota.setBorder(null);
        inputNoHPAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNoHPAnggotaActionPerformed(evt);
            }
        });
        getContentPane().add(inputNoHPAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 400, 30));

        inputProdi.setBackground(new java.awt.Color(222, 217, 186));
        inputProdi.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        inputProdi.setForeground(new java.awt.Color(255, 204, 0));
        inputProdi.setBorder(null);
        inputProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputProdiActionPerformed(evt);
            }
        });
        getContentPane().add(inputProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 382, 400, 30));

        inputFakultas.setBackground(new java.awt.Color(222, 217, 186));
        inputFakultas.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        inputFakultas.setForeground(new java.awt.Color(255, 204, 0));
        inputFakultas.setBorder(null);
        inputFakultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFakultasActionPerformed(evt);
            }
        });
        getContentPane().add(inputFakultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 162, 400, 30));

        inputAlamatAnggota.setBackground(new java.awt.Color(222, 217, 186));
        inputAlamatAnggota.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        inputAlamatAnggota.setForeground(new java.awt.Color(255, 204, 0));
        inputAlamatAnggota.setBorder(null);
        inputAlamatAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAlamatAnggotaActionPerformed(evt);
            }
        });
        getContentPane().add(inputAlamatAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 400, 30));

        inputTahunMasuk.setBackground(new java.awt.Color(222, 217, 186));
        inputTahunMasuk.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        inputTahunMasuk.setForeground(new java.awt.Color(255, 204, 0));
        inputTahunMasuk.setBorder(null);
        inputTahunMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTahunMasukActionPerformed(evt);
            }
        });
        getContentPane().add(inputTahunMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 312, 400, 30));

        btnTambah.setBackground(new java.awt.Color(125, 39, 34));
        btnTambah.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 204, 0));
        btnTambah.setText("Tambah");
        btnTambah.setBorder(null);
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, 220, 50));

        btnSimpan.setBackground(new java.awt.Color(125, 39, 34));
        btnSimpan.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 204, 0));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(null);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, 220, 50));

        btnUbah.setBackground(new java.awt.Color(125, 39, 34));
        btnUbah.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 204, 0));
        btnUbah.setText("Ubah");
        btnUbah.setBorder(null);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        getContentPane().add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 260, 220, 50));

        btnHapus.setBackground(new java.awt.Color(125, 39, 34));
        btnHapus.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 204, 0));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(null);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 330, 220, 50));

        btnBatal.setBackground(new java.awt.Color(125, 39, 34));
        btnBatal.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 204, 0));
        btnBatal.setText("Keluar");
        btnBatal.setBorder(null);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 400, 220, 50));

        jScrollPane1.setForeground(new java.awt.Color(255, 204, 0));
        jScrollPane1.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N

        tabelAnggota.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N
        tabelAnggota.setForeground(new java.awt.Color(255, 204, 0));
        tabelAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Anggota", "Nama Anggota", "Nomor HP Anggota", "Prodi", "Fakultas", "Alamat", "Tahun Masuk"
            }
        ));
        tabelAnggota.setSelectionForeground(new java.awt.Color(255, 204, 0));
        tabelAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelAnggota);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1300, 430));

        bgAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_componen/ui_dataAnggota.png"))); // NOI18N
        getContentPane().add(bgAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void inputIDAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIDAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIDAnggotaActionPerformed

    private void inputNamaAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaAnggotaActionPerformed

    private void inputNoHPAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNoHPAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNoHPAnggotaActionPerformed

    private void inputProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputProdiActionPerformed

    private void inputFakultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFakultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFakultasActionPerformed

    private void inputAlamatAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAlamatAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAlamatAnggotaActionPerformed

    private void inputTahunMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTahunMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTahunMasukActionPerformed

    private void tabelAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAnggotaMouseClicked
        // TODO add your handling code here:
        int row = tabelAnggota.getSelectedRow();
        
//        if (row == -1){
//            return;
//        
//        }
        String idAnggota = (String) tabelAnggota.getValueAt(row, 1);
        inputIDAnggota.setText(idAnggota);
        
        String namaAnggota = (String) tabelAnggota.getValueAt(row, 2);
        inputNamaAnggota.setText(namaAnggota);
        
        String noHPAnggota = (String) tabelAnggota.getValueAt(row, 3);
        inputNoHPAnggota.setText(noHPAnggota);
        
        String prodi = (String) tabelAnggota.getValueAt(row, 4);
        inputProdi.setText(prodi);
        
        String fakultas = (String) tabelAnggota.getValueAt(row, 5);
        inputFakultas.setText(fakultas);
        
        String alamatAnggota = (String) tabelAnggota.getValueAt(row, 6);
        inputAlamatAnggota.setText(alamatAnggota);
        
        String tahunMasuk = (String) tabelAnggota.getValueAt(row, 7);
        inputTahunMasuk.setText(tahunMasuk);
    }//GEN-LAST:event_tabelAnggotaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameAnggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgAnggota;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField inputAlamatAnggota;
    private javax.swing.JTextField inputFakultas;
    private javax.swing.JTextField inputIDAnggota;
    private javax.swing.JTextField inputNamaAnggota;
    private javax.swing.JTextField inputNoHPAnggota;
    private javax.swing.JTextField inputProdi;
    private javax.swing.JTextField inputTahunMasuk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelAnggota;
    // End of variables declaration//GEN-END:variables
}
