/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frameApp;

/**
 *
 * @author Asus
 */
public class frameDataAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frameDataAdmin
     */
    public frameDataAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDataAdmin = new javax.swing.JTable();
        inputIDPetugas = new javax.swing.JTextField();
        inputNamaPetugas = new javax.swing.JTextField();
        inputPassword = new javax.swing.JTextField();
        inputNoHP = new javax.swing.JTextField();
        inputAlamatRumah = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        bgDataAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabelDataAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Petugas", "Nama Petugas", "Password", "Nomor HP", "Alamat Rumah "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelDataAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDataAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelDataAdmin);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 467, 1300, 270));

        inputIDPetugas.setBackground(new java.awt.Color(222, 217, 186));
        inputIDPetugas.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        inputIDPetugas.setBorder(null);
        inputIDPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIDPetugasActionPerformed(evt);
            }
        });
        getContentPane().add(inputIDPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 390, 30));

        inputNamaPetugas.setBackground(new java.awt.Color(222, 217, 186));
        inputNamaPetugas.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        inputNamaPetugas.setBorder(null);
        inputNamaPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaPetugasActionPerformed(evt);
            }
        });
        getContentPane().add(inputNamaPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 390, 30));

        inputPassword.setBackground(new java.awt.Color(222, 217, 186));
        inputPassword.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        inputPassword.setBorder(null);
        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 390, 30));

        inputNoHP.setBackground(new java.awt.Color(222, 217, 186));
        inputNoHP.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        inputNoHP.setBorder(null);
        inputNoHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNoHPActionPerformed(evt);
            }
        });
        getContentPane().add(inputNoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 390, 30));

        inputAlamatRumah.setBackground(new java.awt.Color(222, 217, 186));
        inputAlamatRumah.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        inputAlamatRumah.setBorder(null);
        inputAlamatRumah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAlamatRumahActionPerformed(evt);
            }
        });
        getContentPane().add(inputAlamatRumah, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 390, 30));

        btnTambah.setBackground(new java.awt.Color(125, 39, 34));
        btnTambah.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 204, 0));
        btnTambah.setText("Tambah");
        btnTambah.setBorder(null);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, 220, 50));

        btnSimpan.setBackground(new java.awt.Color(125, 39, 34));
        btnSimpan.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 204, 0));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(null);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, 220, 50));

        btnUbah.setBackground(new java.awt.Color(125, 39, 34));
        btnUbah.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 204, 0));
        btnUbah.setText("Ubah");
        btnUbah.setBorder(null);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        getContentPane().add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 260, 220, 50));

        btnHapus.setBackground(new java.awt.Color(125, 39, 34));
        btnHapus.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 204, 0));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(null);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 330, 220, 50));

        btnBatal.setBackground(new java.awt.Color(125, 39, 34));
        btnBatal.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 204, 0));
        btnBatal.setText("Batal");
        btnBatal.setBorder(null);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 400, 220, 50));

        bgDataAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_componen/uiDataAdmin.png"))); // NOI18N
        getContentPane().add(bgDataAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNamaPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaPetugasActionPerformed

    private void inputIDPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIDPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIDPetugasActionPerformed

    private void inputNoHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNoHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNoHPActionPerformed

    private void inputAlamatRumahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAlamatRumahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAlamatRumahActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void TabelDataAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDataAdminMouseClicked
        // TODO add your handling code here:
        int row = TabelDataAdmin.getSelectedRow();

        //        if (row == -1){
            //            return;
            //
            //        }
        String idPetugas = (String) TabelDataAdmin.getValueAt(row, 1);
        inputIDPetugas.setText(idPetugas);

        String namaPetugas = (String) TabelDataAdmin.getValueAt(row, 3);
        inputNamaPetugas.setText(namaPetugas);

        String password = (String) TabelDataAdmin.getValueAt(row, 4);
        inputPassword.setText(password);

        String nomorHP = (String) TabelDataAdmin.getValueAt(row, 5);
        inputNoHP.setText(nomorHP);

        String alamatRumah = (String) TabelDataAdmin.getValueAt(row, 9);
        inputAlamatRumah.setText(alamatRumah);
    }//GEN-LAST:event_TabelDataAdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameDataAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameDataAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameDataAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameDataAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameDataAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelDataAdmin;
    private javax.swing.JLabel bgDataAdmin;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField inputAlamatRumah;
    private javax.swing.JTextField inputIDPetugas;
    private javax.swing.JTextField inputNamaPetugas;
    private javax.swing.JTextField inputNoHP;
    private javax.swing.JTextField inputPassword;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
