/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frameApp;

/**
 *
 * @author Septiancesare
 */
public class frameMenu extends javax.swing.JFrame {

    /**
     * Creates new form frameMenu
     */
    public frameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDataAnggota = new javax.swing.JButton();
        btnPeminjaman = new javax.swing.JButton();
        btnPengembalian = new javax.swing.JButton();
        btnDataAdmin = new javax.swing.JButton();
        btnDataBuku = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDataAnggota.setBackground(new java.awt.Color(251, 205, 31));
        btnDataAnggota.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnDataAnggota.setForeground(new java.awt.Color(125, 39, 34));
        btnDataAnggota.setText("DATA ANGGOTA");
        jPanel1.add(btnDataAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 300, 180));

        btnPeminjaman.setBackground(new java.awt.Color(251, 205, 31));
        btnPeminjaman.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnPeminjaman.setForeground(new java.awt.Color(125, 39, 34));
        btnPeminjaman.setText("PEMINJAMAN BUKU");
        btnPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeminjamanActionPerformed(evt);
            }
        });
        jPanel1.add(btnPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 300, 180));

        btnPengembalian.setBackground(new java.awt.Color(251, 205, 31));
        btnPengembalian.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnPengembalian.setForeground(new java.awt.Color(125, 39, 34));
        btnPengembalian.setText("PENGEMBALIAN BUKU");
        btnPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengembalianActionPerformed(evt);
            }
        });
        jPanel1.add(btnPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 193, 310, 170));

        btnDataAdmin.setBackground(new java.awt.Color(251, 205, 31));
        btnDataAdmin.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnDataAdmin.setForeground(new java.awt.Color(125, 39, 34));
        btnDataAdmin.setText("DATA ADMIN");
        jPanel1.add(btnDataAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 300, 180));

        btnDataBuku.setBackground(new java.awt.Color(251, 205, 31));
        btnDataBuku.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnDataBuku.setForeground(new java.awt.Color(125, 39, 34));
        btnDataBuku.setText("DATA BUKU");
        jPanel1.add(btnDataBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 300, 180));

        btnKeluar.setBackground(new java.awt.Color(251, 205, 31));
        btnKeluar.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(125, 39, 34));
        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 430, 310, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_componen/uiMenu.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jLabel1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabel1CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1CaretPositionChanged

    private void btnPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeminjamanActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        frameLogin login = new frameLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengembalianActionPerformed
        // TODO add your handling code here:
        framePengembalian pengembalian = new framePengembalian();
        pengembalian.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPengembalianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataAdmin;
    private javax.swing.JButton btnDataAnggota;
    private javax.swing.JButton btnDataBuku;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPeminjaman;
    private javax.swing.JButton btnPengembalian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
